// Do not edit. This file is machine generated by the Resource DLL Wizard.

library client;

{ITE} {DFMFileType} {UI\CustomView.dfm}
{ITE} {DFMFileType} {UI\Dialogs\FrmLogin.dfm}
{ITE} {DFMFileType} {UI\Dialogs\FrmWaiting.dfm}
{ITE} {DFMFileType} {UI\Main.dfm}
{ITE} {DFMFileType} {UI\SNSView.dfm}
{ITE} {RCFileType} {client_DRC.rc}

{$R 'UI\CustomView.dfm' CustomViewer:TFrame}
{$R 'UI\Dialogs\FrmLogin.dfm' LoginForm:TForm}
{$R 'UI\Dialogs\FrmWaiting.dfm' WaitingForm:TForm}
{$R 'UI\Main.dfm' MainForm:TForm}
{$R 'UI\SNSView.dfm' SNSViewer:TForm(CustomViewer)}
{$R 'client_DRC.res' 'client_DRC.rc'}

{$E ZHI}

begin
end.